linters-settings:
  gosec:
    excludes:
      - G306
      - G107

linters:
  disable:
    - deadcode
    - unused
    - varcheck
    - gomnd
    - gochecknoglobals
    - revive

    - forcetypeassert
    - cyclop
    - unparam
    - lll
    - funlen
    - goconst
    - dupl

    - golint
    - interfacer
    - maligned
    - scopelint
    - exhaustivestruct

  enable-all: true