#!/usr/bin/env bash

log() {
    echo -e "$1[.]${RESET} $2"
}

success_log() {
    echo -e "$1[^]${RESET} $2"
}

input() {
    echo -e -n "$1[?]${RESET} $3: "
    read -r "$2"
}

chap_log() {
    echo
    echo -e "${BOLD}$1 ${WHITE}$2${RESET}"
}

GREEN="\033[32m"
WHITE="\033[37m"
RED="\033[31m"
CYAN="\033[36m"
BOLD="\033[1m"
RESET="\033[0m"

log "$CYAN" "Welcome to the Go install script."

if [ ! "$USER" = "root" ]; then
    log "$RED" "You need to run this script as root. Usually this means prefixing the command with sudo."
    exit 1
fi

log "$CYAN" "Checking OS info..."

OS=$(uname -s)
arch=$(uname -m)

log "$CYAN" "OS: ${OS}"
log "$CYAN" "Architecture: ${arch}"

final_OS=""
final_arch=""

case $OS in
Darwin)
    log "$CYAN" "Darwin detected"
    final_OS="darwin"
    ;;
Linux)
    log "$CYAN" "Linux detected"
    final_OS="linux"
    ;;
*)
    log "$RED" "Unsupported OS"
    exit 1
    ;;
esac

case $arch in
x86_64)
    log "$CYAN" "x86_64 (amd64) detected"
    final_arch="amd64"
    ;;
arm64)
    log "$CYAN" "arm64 detected"
    final_arch="arm64"
    ;;
arm)
    log "$CYAN" "arm detected"
    final_arch="armv6l"
    ;;
*)
    log "$RED" "Unsupported architecture"
    exit 1
    ;;
esac

url="https://dl.google.com/go/go1.18.2.$final_OS-$final_arch.tar.gz"

log "$CYAN" "URL: $url"

log "$CYAN" "Deleting previous installation if present..."
rm -rf "/usr/local/go"

log "$CYAN" "Downloading Go..."
curl "$url" -o "/tmp/go.tar.gz"

log "$CYAN" "Unpacking archive..."
mkdir -p "/usr/local"
tar -C /usr/local -xzf "/tmp/go.tar.gz"

function appendPathAdd {
    log "$CYAN" "Checking if $BOLD$1$RESET exists..."
    if [ -f "$HOME/$1" ]; then
        log "$CYAN" "Appending to $BOLD$1$RESET..."
        printf "\n\n# Add ~/.local/bin to PATH (auto-generated by indiepkg's go installer)\nexport PATH=\"  q/usr/local/go/bin:\$PATH\"" >>"$HOME/$1"
    fi
}

log "$CYAN" "Adding $BOLD/usr/local/go/bin$RESET to PATH..."
appendPathAdd ".profile"
appendPathAdd ".zprofile"
appendPathAdd ".zshrc"
appendPathAdd ".bashrc"
appendPathAdd ".kshrc"

log "$CYAN" "Cleaning up..."
rm -rf "/tmp/go.tar.gz"

log "$GREEN" "Done! Installed go successfully."