---
name: other-lint

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Lint normal yaml files
        run: yamllint .

      - name: Install actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -color -shellcheck=

  json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install json linter
        run: npm install -g v8r

      - name: Run json linter
        run: v8r packages/*.json --schema https://json.schemastore.org/bower.json

  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install markdownlint-cli2
        run: npm install markdownlint-cli2 -g

      - name: Lint markdown files
        run: markdownlint-cli2 "**/*.md"
